### ISSUE TITLE
能设置滚动到底部自动加载吗？

### ISSUE THREAD

**Issue by Minori-ty** [NekoChanTaiwan/Tampermonkey-Scripts#5]
如题，或者一次性加载所有图片，不用去手动翻页。

**Comment by aaronlin0122** [comment]
![image](https://user-images.githubusercontent.com/47508893/150654322-9be876a8-5ed0-41f2-8f00-b605c470d027.png)

**Comment by Minori-ty** [comment]
> ![image](https://user-images.githubusercontent.com/47508893/150654322-9be876a8-5ed0-41f2-8f00-b605c470d027.png)
> 

好的，我说之前好像可以滚动的，原来是这里

**Comment by Minori-ty** [comment]
你可以把加载成功的notion取消掉吗？

**Comment by Minori-ty** [comment]
并且把单页页面设置成100%

**Comment by Minori-ty** [comment]
自己的收藏那里的话，也可以做成无限滚动

**Comment by aaronlin0122** [comment]
目前有其他項目正在寫，該項目暫時不會碰。

**Comment by aaronlin0122** [comment]
https://github.com/NekoChanTaiwan/nHentai-Enhanced/commit/df20eca12e5c166e435a85434f11c36bca248934 取消初始化通知
https://github.com/NekoChanTaiwan/nHentai-Enhanced/commit/db7fa3b664ffaa24b900b3186d3331b2d7b42648 支援搜尋頁面無限加載
https://github.com/NekoChanTaiwan/nHentai-Enhanced/commit/7fcb17db0b92053f8718baff24ed87a13cfa5cbd 支援收藏頁面無限加載

**Comment by aaronlin0122** [comment]
之後會用 ts 重構，現在這樣體積有點大，而且效能也不太滿意。

此項目是我之前學習 js 的項目，所以很多地方寫得很不好，維護起來挺麻煩的😢
若有興趣參與可以在 Discord 找我 `NekoChan#2851` 🤣

**Comment by Minori-ty** [comment]
> 之後會用 ts 重構，現在這樣體積有點大，而且效能也不太滿意。
> 
> 此項目是我之前學習 js 的項目，所以很多地方寫得很不好，維護起來挺麻煩的😢
> 若有興趣參與可以在 Discord 找我 `NekoChan#2851` 🤣

好的

**Comment by Minori-ty** [comment]
> 之後會用 ts 重構，現在這樣體積有點大，而且效能也不太滿意。
> 
> 此項目是我之前學習 js 的項目，所以很多地方寫得很不好，維護起來挺麻煩的😢 若有興趣參與可以在 Discord 找我 `NekoChan#2851` 🤣

可以写成浏览器插件，你开个项目一起开发把
